# Generated by Django 3.2 on 2022-05-27 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desciption', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=11, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
            ],
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('f600c40c-d086-485b-ba71-9f3425522570'), editable=False)),
                ('is_reserve', models.BooleanField(default=False)),
                ('is_rent', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.rack')),
                ('rent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent', to=settings.AUTH_USER_MODEL)),
                ('reserve', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
