# Generated by Django 3.2 on 2022-05-27 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('93f6239c-2a71-4609-adb7-16733917a8a4')),
        ),
    ]
